name = "batz"
license = "mpl-2.0"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "very epic and super cool"
homepage = "https://batz.cool/"
min_version = "0.41.0"

[author]
  name = "batz"
  homepage = "https://batz.cool/"
